# Generated by Django 4.2.16 on 2024-10-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
